// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNj8c2EQU6bxtqP2CPvrvLyhqgfGlFPzs',
    appId: '1:300031739094:web:0dfd8f09bebdc6c2667577',
    messagingSenderId: '300031739094',
    projectId: 'realme-e936e',
    authDomain: 'realme-e936e.firebaseapp.com',
    storageBucket: 'realme-e936e.appspot.com',
    measurementId: 'G-NMYBVWEK07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRYmNALkXNVQnY6lAaPZ-h9kdeRcx6zEE',
    appId: '1:300031739094:android:aaf330ea8139dd5b667577',
    messagingSenderId: '300031739094',
    projectId: 'realme-e936e',
    storageBucket: 'realme-e936e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBWQ2eTf2qwpvHPmpa6XZOzHylGfLI5yA',
    appId: '1:300031739094:ios:99111a854ecc6dc0667577',
    messagingSenderId: '300031739094',
    projectId: 'realme-e936e',
    storageBucket: 'realme-e936e.appspot.com',
    iosClientId: '300031739094-mn7d9ljvriuhgfrvo75gcqg0vigf4oj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.realme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBWQ2eTf2qwpvHPmpa6XZOzHylGfLI5yA',
    appId: '1:300031739094:ios:99111a854ecc6dc0667577',
    messagingSenderId: '300031739094',
    projectId: 'realme-e936e',
    storageBucket: 'realme-e936e.appspot.com',
    iosClientId: '300031739094-mn7d9ljvriuhgfrvo75gcqg0vigf4oj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.realme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNj8c2EQU6bxtqP2CPvrvLyhqgfGlFPzs',
    appId: '1:300031739094:web:d08bec3e0e9f0863667577',
    messagingSenderId: '300031739094',
    projectId: 'realme-e936e',
    authDomain: 'realme-e936e.firebaseapp.com',
    storageBucket: 'realme-e936e.appspot.com',
    measurementId: 'G-HJK5R4V536',
  );

}